[package]
name = "chain"
version = "0.1.0"
authors = ["Octavian Oncescu <octavonce@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
elastic-array = "0.10.0"
byteorder = "1.2.7"
lazy_static = "1.4.0"
triomphe = { git = "https://github.com/octavonce/triomphe" }
lru = "0.7.1"
rlp = "0.3.0"
parking_lot = "0.7.1"
hex = "0.3.2"
log = "0.4.0"
patricia-trie = "0.3.0"
account = { path = "../account" }
crypto = { path = "../crypto" }
miner = { path = "../miner" }
transactions = { path = "../transactions" }
constants = { path = "../constants" }
persistence = { path = "../persistence" }
bin-tools = { path = "../util/bin-tools/" }
hashdb = "0.3.0"
rand = "^0.6.0"
quickcheck = "0.7.2"
static_assertions = "1"
hashbrown = { git = "https://github.com/octavonce/hashbrown", features = ["serde", "rayon"] }
graphlib = { version = "0.6.0", features = ["dot"] }
test-helpers = { path = "../util/test-helpers" }

[dev-dependencies]
rayon = "1.2.0"
criterion = "0.2.1"
tempdir = "0.3.7"
rocksdb = "0.13.0"

[dev-dependencies.miner]
features = ["test"]
path = "../miner" 

[dev-dependencies.transactions]
features = ["test"]
path = "../transactions" 

[[bench]]
name = "chain_benchmarks"
path = "bench/chain_bench.rs"
harness = false

[features]
test = []